sudo: required
services: 
  - docker
language: node_js
node_js:
  - 8
before_install:
  - docker build -t docker-react-app -f Dockerfile.dev .

script:
  - docker run docker-react-app npm run test -- --coverage